customhost = "employee.cl6eo5yvybnz.ap-southeast-2.rds.amazonaws.com"
customuser = "vprime"
custompass = "vprime1234"
customdb = "employee"
custombucket = "addvprimeemployee"
customregion = "ap-southeast-2a"
