customhost = "employee-vprime.coaa0fn3na3v.us-east-2.rds.amazonaws.com"
customuser = "vprime"
custompass = "vprime1234"
customdb = "employeevprime"
custombucket = "imgvprimeemployee"
customregion = "us-east-2a"
